version: '3.8'

services:
  gateway:
    build: ./gateway
    ports:
      - "5000:5000"
  
  password_generator:
    build: ./tools/password-generator
    ports:
      - "5007:5007"

  ip_catcher:
    build: ./tools/ip-catcher
    ports:
      - "5002:5002"
