# fly.toml app configuration file generated for hello-friend on 2025-06-27T17:11:04+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hello-friend'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 5002
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
